# Bazel WORKSPACE file with examples for three common language rules

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Python Rules
http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.26.0/rules_python-0.26.0.tar.gz",
    sha256 = "05cf8f88fac00edab5b921854c2a00e67c2cba76f7ea61e29a52957ac059c555",
)
load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()

# Go Rules
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "bfc338fc0f7d36a7b36b48933638ff5354f9fb080be7c3e8926c26ccab16c547",
    urls = [
        "https://github.com/bazelbuild/rules_go/releases/download/v0.47.0/rules_go-v0.47.0.zip",
    ],
)
load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()

# JavaScript/Yarn Rules (rules_nodejs)
http_archive(
    name = "build_bazel_rules_nodejs",
    url = "https://github.com/bazelbuild/rules_nodejs/releases/download/6.3.0/rules_nodejs-6.3.0.tar.gz",
    sha256 = "cf086330a89ec3752a7f9c14624ab1dea4b4fb447dabf345942f024046b04695",
)
load("@build_bazel_rules_nodejs//:index.bzl", "nodejs_register_toolchains", "npm_install")
nodejs_register_toolchains()
# If you want to use npm or yarn dependencies in your project, add an npm_install below

# Add more rules or custom repository logic here as needed.
